/*

    389. Find the Difference
    
    Source : https://leetcode.com/problems/find-the-difference/
    
    Statement :
              You are given two strings s and t.

              String t is generated by random shuffling string s and then add one more letter at a random position.

              Return the letter that was added to t.



              Example 1:

              Input: s = "abcd", t = "abcde"
              Output: "e"
              Explanation: 'e' is the letter that was added.
              Example 2:

              Input: s = "", t = "y"
              Output: "y"
              
*/
// Storing the ASCII values, adding and subtrcting from strings s, t
   
class Solution {
public:
    char findTheDifference(string s, string t) {
        int ans = 0;
        for(int i=0;i<s.size();i++) {
            ans = ans - s[i];
            ans = ans + t[i];
        }
        ans = ans + t[s.size()];
        return ans;
    }
};
